# -*- coding: utf-8 -*-
"""Copy of week2_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQh96R-6Z163O7yw2P09I5pmuAK3AXab
"""

import pandas as pd
import numpy as np
#Q1
df= pd.read_csv('/Dataset.csv')
print("first five records:")
display(df.head())
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)



print("First 5 Records:")
print(df.head())

#q2
print("Rows and Columns:")
print(df.shape)

#q3.
print("Column Names:")
print(df.columns.tolist())

#q4.
print("Numerical Features:")
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(numerical_cols)

print("\nCategorical Features:")
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(categorical_cols)

#q5.
print("Missing Values:")
print(df.isnull().sum())

#q6.

print("Average Age:")
print(df['Age'].mean())

#q7.
print("Average Watch Hours Per Week:")
print(df['WatchHoursPerWeek'].mean())

#q8
print("Average Monthly Spending:")
print(df['MonthlySpend'].mean())

#q9
print("Users in Each Subscription Category:")
print(df['SubscriptionType'].value_counts())

#q10
renew_percent = (df['SubscriptionRenewed'].value_counts(normalize=True) * 100)
print("Renewal Percentage:")
print(renew_percent)


#q11
print("Encoding Categorical Features")

df_encoded = df.copy()

label_encoders = {}

for col in df_encoded.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])
    label_encoders[col] = le

print("Categorical Features Converted Successfully")

#q12

X = df_encoded.drop(columns=['SubscriptionRenewed'])
y = df_encoded['SubscriptionRenewed']

print("Features (X):")
print(X.columns.tolist())

print("\nTarget (y):")


#13

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)



#q14

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

print("Decision Tree Model Trained Successfully")

#q15

y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:")
print(round(dt_accuracy * 100, 2), "%")

#q16

cm = confusion_matrix(y_test, y_pred_dt)

print("Confusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))



#q17

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

knn_accuracy = accuracy_score(y_test, y_pred_knn)

print("KNN Model Trained Successfully")

#18

print("Decision Tree Accuracy :", round(dt_accuracy * 100, 2), "%")
print("KNN Accuracy           :", round(knn_accuracy * 100, 2), "%")

if knn_accuracy > dt_accuracy:
    print("KNN performs better.")
elif dt_accuracy > knn_accuracy:
    print("Decision Tree performs better.")
else:
    print("Both models have equal accuracy.")



#19

# Predict Monthly Spending

X_reg = df_encoded.drop(columns=['SubscriptionRenewed'])
y_reg = df_encoded['SubscriptionRenewed']

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

lr_model = LinearRegression()

lr_model.fit(X_train_reg, y_train_reg)

print("Linear Regression Model Trained Successfully")

#20

# Use first test record as example new user
new_user = X_test_reg.iloc[[0]]

predicted_spending = lr_model.predict(new_user)

print("Predicted Monthly Spending:")
print(round(predicted_spending[0], 2))

print("\nInterpretation:")
print(
    f"The model predicts that the user's monthly spending "
    f"will be approximately {round(predicted_spending[0], 2)} units."
)

#Business Reflection Questions
#1. Which factors appear to influence subscription renewal the most?
#ans. monthly spend
#2. Why is subscription renewal a classification problem?
# because the answer is a discrete yes or no
#3. Why is monthly spending a regression problem?
#ans. because the answer is a continous numeric tye
#4. Which algorithm performed better for renewal prediction?
# both are equal
#5. How could the platform use these predictions to improve customer retention?
#ans. to gain insights such as target users, relation between the data and its effect on revenue, steps to increase revenue etc.